### ISSUE TITLE
Crash or hangs if filenames contain non-UTF8 characters

### ISSUE THREAD

**Issue by lparcq** [funbiscuit/spacedisplay-rs#6]
When a file name contains non-UTF8 characters in a UTF8 locale (ex: latin1), the command crashes or hangs. I haven't found the conditions that makes it either crash or hang.

When it crashes, the error is:
`thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/diskscan-0.3.0/src/scanner.rs:295:67`

**Comment by funbiscuit** [comment]
Thanks for the report.
Condition is exactly at `scanner.rs:295` - calling `unwrap` on `Option<&str>` which is `None`. Since filename was not utf8 so `to_str()` returned `None`
In this app I everywhere assume that all file paths are well formed utf8 strings which obviously not always the case, but it was good enough assumption at the start (and in my cases that was always correct).
Some refactor needs to be done to switch from `String` to `OsString`/`PathBuf` that will fix the problem.

**Comment by lparcq** [comment]
Thanks. Maybe just writing an error instead of panicking would be enough and much easier to implement.
